### ISSUE TITLE
Conversion to molden

### ISSUE THREAD

**Issue by Brohmsen** [TREX-CoE/trexio_tools#60]
Hello dear TREXIO developer, 

I am introducing myself to TREXIO and want to convert a TREXIO file towards molden, which is currently not working. Here the command I'm parsing and the file I am using is attached: 

```
trexio convert-to -t molden -o pyscf.molden pyscf.trexio
```

The error I get is the following: 

```
NameError: name 'basis_shell_num' is not defined
```

What am I doing wrong ? 

Kind regards, 
Elias Brohmer

[pyscf.trexio.zip](https://github.com/user-attachments/files/23162081/pyscf.trexio.zip)

**Comment by scemama** [comment]
Hello,
the trexio-tools available with pip has a bug that produces this error, and it has been fixed. If you use the code from the github repository, it should work fine.

@q-posev : Can you please update the pip of trexio-tools?

**Comment by q-posev** [comment]
@scemama Done!

**Comment by Brohmsen** [comment]
I tried to convert from TrexIO towards molden and it is still not working. Either from pip nor from your git code. I'm still using the same data as stated above. Am I doing something wrong ? 

I did uninstalled the old version via:
```
pip uninstall trexio-tools
```

and I also tried to install from the source code via:
```
pip install git+https://github.com/TREX-CoE/trexio_tools
```
and reinstalling via pip:
```
pip install trexio-tools
```
I also reinstalled trexio in general but this also didnt help.

**Comment by q-posev** [comment]
@Brohmsen I do no think that the TREXIO -> Molden converter has been extensively tested, so it is possible that a breaking change has been introduced in the past. I can have a look in the coming weeks.

Did you check the validity of your `pyscf.trexio` TREXIO file using the `check-basis` or `check-mos` CLI routines provided by `trexio-tools`?

**Comment by Brohmsen** [comment]
Yes, there is a problem with the file provided by pyscf. I also tried the file from the benzene tutorial (https://trex-coe.github.io/trexio/tutorial_benzene.html), which also is not working.
